--- #YAML:1.0
name:                MP3-Podcast
version:             0.06_1aa
abstract:            Perl extension for podcasting directories full of MP3 files
license:             ~
author:              
    - Juan Julian Merelo Guervos <jmerelo@geneura.ugr.es>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    MP3::Info:                     1.13
    URI:                           0
    XML::RSS:                      1.05
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
